name: Scaleshifter
version: '${version}'
main: net.hynse.scaleshifter.Scaleshifter
api-version: '1.20'
folia-supported: true
commands:
  scaleplayer:
    description: Set the scale of a player.
    usage: /scaleplayer <playername> <value>
    permission: scaleshifter.scaleplayer

  scale:
    description: Set your own scale.
    usage: /scale <value>
    permission: scaleshifter.scale

  scalegui:
    description: Open gui.
    usage: /scalegui
    permission: scaleshifter.scalegui

  scaleguiplayer:
    description: Open gui.
    usage: /scaleguiplayer <player>
    permission: scaleshifter.scaleguiplayer

permissions:
  scaleshifter.scaleplayer:
    description: Allows a player to set the scale of another player.
    default: op

  scaleshifter.scale:
    description: Allows a player to set their own scale.
    default: op

  scaleshifter.scalegui:
    description: Allows a player to open gui.
    default: op

  scaleshifter.scaleguiplayer:
    description: Allows a player to open gui for other player.
    default: op